name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - uses: dtolnay/rust-toolchain@1.89.0
    - uses: actions/setup-python@v6
      with:
        python-version: '3.x'
    - name: Build
      working-directory: ./PSO
      env:
        PYO3_PYTHON: python
      run: cargo build --locked --verbose --release --lib
    - uses: actions/upload-artifact@v4
      with: 
        name: libpso.so
        path: PSO/target/release/libpso.so  
