name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with: 
        toolchain: nightly
        default: true    
    - name: Build
      run: |
        cd ./PSO
        cargo build --verbose --release
    - uses: actions/upload-artifact@v4
      with: 
        name: libpso.so
        path: PSO/target/release/libpso.so  
